
import React, { useState } from 'react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import GrammarChecker from '@/components/writing/GrammarChecker';
import EssayCoach from '@/components/writing/EssayCoach';
import AiDetector from '@/components/writing/AiDetector';
import TextHumanizer from '@/components/writing/TextHumanizer';
import ExamPaperGenerator from '@/components/writing/ExamPaperGenerator';
import WritingDashboard from '@/components/writing/WritingDashboard';

const WritingTools = () => {
  const [activeTab, setActiveTab] = useState('dashboard');

  return (
    <div className="container mx-auto p-6 space-y-8 max-w-7xl">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tight bg-gradient-to-br from-foreground to-foreground/80 bg-clip-text text-transparent">
          Writing Tools
        </h1>
        <p className="text-muted-foreground text-lg">
          Comprehensive suite of writing assistants, checkers, and generators
        </p>
      </div>

      <Tabs defaultValue="dashboard" value={activeTab} onValueChange={setActiveTab} className="space-y-4">
        <TabsList className="grid grid-cols-3 md:grid-cols-6 gap-2">
          <TabsTrigger value="dashboard" className="text-xs md:text-sm">Dashboard</TabsTrigger>
          <TabsTrigger value="essay-coach" className="text-xs md:text-sm">Essay Coach</TabsTrigger>
          <TabsTrigger value="grammar" className="text-xs md:text-sm">Grammar</TabsTrigger>
          <TabsTrigger value="ai-detector" className="text-xs md:text-sm">AI Detector</TabsTrigger>
          <TabsTrigger value="humanizer" className="text-xs md:text-sm">Humanizer</TabsTrigger>
          <TabsTrigger value="exam-generator" className="text-xs md:text-sm">Exam Generator</TabsTrigger>
        </TabsList>
        
        <TabsContent value="dashboard" className="space-y-4">
          <WritingDashboard />
        </TabsContent>
        
        <TabsContent value="essay-coach" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Essay Writing Coach</CardTitle>
              <CardDescription>Get guidance on structure, style, and improvement suggestions</CardDescription>
            </CardHeader>
            <CardContent>
              <EssayCoach />
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="grammar" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Grammar Checker</CardTitle>
              <CardDescription>Advanced grammar, spelling, and style checking</CardDescription>
            </CardHeader>
            <CardContent>
              <GrammarChecker />
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="ai-detector" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>AI Detection</CardTitle>
              <CardDescription>Check if text was generated by AI</CardDescription>
            </CardHeader>
            <CardContent>
              <AiDetector />
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="humanizer" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Text Humanizer</CardTitle>
              <CardDescription>Make AI-generated content sound more human</CardDescription>
            </CardHeader>
            <CardContent>
              <TextHumanizer />
            </CardContent>
          </Card>
        </TabsContent>
        
        <TabsContent value="exam-generator" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Exam Paper Generator</CardTitle>
              <CardDescription>Create custom exams from your study materials</CardDescription>
            </CardHeader>
            <CardContent>
              <ExamPaperGenerator />
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default WritingTools;
