// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofzacetifoqgfpjtumes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9memFjZXRpZm9xZ2ZwanR1bWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjA3NzcsImV4cCI6MjA2MTEzNjc3N30.7gY1bEMivVn1nUN9dQrZZekWlyROSsJuEZozNYkkTgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);